# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83a05e0af14f83c76ba246fb9d5f0e15b931cc05318fe4661241a34deef051be928bb8c1c593e37ef5a3fac8013436065d6bb0a0bea9a13a7f3b3619f6fad342

test:
  secret_key_base: cf87c9756210840aaf109ee2aa90f98202e3ba9a294db1f187b3a523781b8ef7394584190b5530aacc8c75726bb61281d72f08643709cf129ce12999a202c404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
